### ISSUE TITLE
Dictionary access fails

### ISSUE THREAD

**Issue by ivanhernandez** [SwiftForWindows/SwiftForWindows#10]
When running this program:

```swift
let dic : [String: String?] = ["a": "It is a", "b" : nil]

let a = dic["a"]
// let b = dic["b"]
// let c = dic["c"]

print(a as Any)
//print(b as Any)
//print(c as Any)
```

A ``Segmentation fault`` error happens. 

I was expecting:

```
Optional(Optional("It is a"))
```

Although did not check behaviour in XCode, yet.

**Comment by tinysun212** [comment]
Thanks for your reporting this bug.
I was able to reproduce the problem with your test code.
I'm sorry I could not fix the bug quickly. The bug will be fixed when next version released.

Best regards,
Han Sangjin

**Comment by tinysun212** [comment]
This bug is fixed. Please try v1.7 and confirm this issue is resolved.

**Comment by tinysun212** [comment]
@ivanhernandez Could you confirm if this bug is resolved?

**Comment by ivanhernandez** [comment]
@tinysun212 I have confirmed that after uncommenting all the code, I obtain this output

```swift
Optional(Optional("It is a"))
Optional(nil)
nil
```

Just as I expected. 

**Issue is solved**.

Thanks for your effort.
