### ISSUE TITLE
How do I import libraries such as UIKit?

### ISSUE THREAD

**Issue by rustyhaidu** [SwiftForWindows/SwiftForWindows#11]
I've tried following a swift tutorial, and when importing the UIKit, it gives me the error - no such module 'UIKit'. Please help

**Comment by tinysun212** [comment]
You should not import UIKit or AppKit because they are not ported to Linux and Windows. However, the [Foundation](https://swift.org/core-libraries/#foundation) is implemented for Linux and the porting work is in progress for Windows.
