### ISSUE TITLE
How compile more files

### ISSUE THREAD

**Issue by ivlevAstef** [SwiftForWindows/SwiftForWindows#12]
I'm trying to compile a program consisting of several files:
swiftc main.swift file1.swift file2.swift -o Output.exe

The compilation passes, but during linking problems:
file1-93c003.o:(.text+0x330): multiple definition of `swift_rt_swift_retain'
main-e1cdbf.o:(.text+0x370): first defined here
file1-93c003.o:(.text+0x340): multiple definition of `swift_rt_swift_release'
main-e1cdbf.o:(.text+0x380): first defined here
file1-93c003.o:(.rdata+0xd8): multiple definition of `__swift_reflection_version'
main-e1cdbf.o:(.rdata+0x22): first defined here
file2-9c3271.o:(.text+0x3f0): multiple definition of `swift_rt_swift_allocObject'
file1-93c003.o:(.text+0x140): first defined here
file2-9c3271.o:(.text+0x800): multiple definition of `swift_rt_swift_retain'
main-e1cdbf.o:(.text+0x370): first defined here
file2-9c3271.o:(.text+0x810): multiple definition of `swift_rt_swift_release'
main-e1cdbf.o:(.text+0x380): first defined here
file2-9c3271.o:(.text+0x14e0): multiple definition of `swift_rt_swift_slowAlloc'
file1-93c003.o:(.text+0x6b0): first defined here
file2-9c3271.o:(.text+0x14f0): multiple definition of `swift_rt_swift_slowDealloc'
file1-93c003.o:(.text+0x6c0): first defined here
file2-9c3271.o:(.rdata+0x370): multiple definition of `__swift_reflection_version'
main-e1cdbf.o:(.rdata+0x22): first defined here
...

I have not considered?

**Comment by tinysun212** [comment]
Try using the linker option.
```
swiftc main.swift file1.swift file2.swift -o Output.exe -Xlinker --allow-multiple-definition
```

**Comment by ivlevAstef** [comment]
Thanks.
