### ISSUE TITLE
One Question (use windows library)

### ISSUE THREAD

**Issue by ivlevAstef** [SwiftForWindows/SwiftForWindows#13]
can I compile to use **windows** libraries?
`swiftc main.swift -L. -lwindowslib`

Where windowslib it's file: `libwindowslib.lib` compiled by visual studio.

And if not, how I can compile compatible library written on cpp?
I tried clang++ and ld, but quickly failed...

**Comment by tinysun212** [comment]
The `Swift for Windows 1.6` is built on the [MinGW-w64](https://sourceforge.net/projects/mingw-w64/) C/C++ Runtime which is not compatible with Visual Studio C++ runtime. 

Moreover, the `clang++` contained in the 'Swift for Windows 1.6' is the specially made small-sized ld-driver which is used only for 'Linking' and can not compile the C++ source. You should use the real clang++ compiler package distributed for the MinGW-w64.

You can only call `extern "C"` functions in the Swift. If you want to use the C++ class and object, you should wrap them in your C functions.

Here is an example.

Foo.cpp
```c++
class MyDiv
{
public:
    MyDiv(int a, int b) {
        result_ = float(a)/b;
    }
	
    float GetResult() {
        return result_;
    }
private:
    float result_;	
};

extern "C" float Foo_in_c(int a, int b)
{
    MyDiv  my_div(a, b);
    return my_div.GetResult();
}
```

main.swift
```swift

@_silgen_name("Foo_in_c")
func Foo(_:CInt, _:CInt) -> CFloat

let res = Foo(123, 456)
print(res)
```

Run in the `Swift Tools Command Prompt`
```
C:\Swift\My Programs>clang++-4.0.0 -c Foo.cpp

C:\Swift\My Programs>swiftc main.swift Foo.o

C:\Swift\My Programs>main
0.269737
```

You can also use your library.
```
C:\Swift\My Programs>ar cr libfoo.a Foo.o

C:\Swift\My Programs>swiftc main.swift -L. -lfoo
```

Thanks

**Comment by ivlevAstef** [comment]
Thanks. True, I have used `g++` not `clang++` :)
