### ISSUE TITLE
Incorrect output by String(format:)

### ISSUE THREAD

**Issue by kanchudeep** [SwiftForWindows/SwiftForWindows#33]
```swift
import Foundation

let i:Int = 1234,
	d:Double = 12.34

print(String(format: "%d, %f", i, d))
```
Gives result as:
`0, 0.000000`

Instead of:
`1234, 12.340000`

**Comment by tinysun212** [comment]
Thanks for your reporting this bug.
I was able to reproduce the problem with your test code.
The bug will be fixed in the next version.

Best regards,
Han Sangjin

**Comment by kanchudeep** [comment]
Thank you...
Just curios... Any timeline for next version?

**Comment by tinysun212** [comment]
Fixing another serious bug, the package will be released in a few days after. By the way, this bug was fixed in my repo and the package will be based on the compiler v4.0.3.

**Comment by tinysun212** [comment]
The new 'Swift for Windows v1.8' is released. Would you try it?

**Comment by kanchudeep** [comment]
Will surely try it!

**Comment by kanchudeep** [comment]
`%d` and `%f` seem to be working as expected in version `1.8`!

Thanks!!!

However, `%@`, e.g.: `print(String(format: "%@, %@", "Hello", "world"))` throws `error: argument type 'String' does not conform to expected type 'CVarArg'`.

The same code works in `Xcode` and is officially [supported](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html).

**Comment by tinysun212** [comment]
Thanks for your report.
I confirmed that the same error occurs in the swift-4.0.3-RELEASE on Linux.
This bug is already reported for Linux. (https://bugs.swift.org/browse/SR-957)
I think it should be fixed first on Linux.

**Comment by kanchudeep** [comment]
OK...

Since this issue (`%@`) is not part of initial issue, I think it can be marked as fixed.
