### ISSUE TITLE
Init Double from String did not work.

### ISSUE THREAD

**Issue by damuellen** [SwiftForWindows/SwiftForWindows#38]
`print(Double("42")!) ` crash
or 
`print(Float("42")!) ` crash
but
`print(Int("42")!) ` fine

Creating a floating point value from a string, does not work for me.

**Comment by tinysun212** [comment]
Thanks for your report.
I'll notify you if I fix this.

**Comment by tinysun212** [comment]
I modified the source.
You can download the updated compiler `swift.zip` from [here](https://ci.appveyor.com/project/tinysun212/swift-compiler-builder/build/1.0.12/artifacts). (https://ci.appveyor.com/project/tinysun212/swift-compiler-builder/build/1.0.12/artifacts)
The zip file has only the compiler. To install, extract the directories from the zip file and overwrite (not replace) them to `Swift\usr\bin` and `Swift\usr\lib`.

Could you test again and let me know the result?

**Comment by damuellen** [comment]
A new error occurs, when I try to run SwiftForWindows.exe

The procedure entry point_create_locale could not be located in dynamic link library msvcrt.dll.

**Comment by tinysun212** [comment]
Thanks for the test.
Does any `swift foo.swift` run on the `Swift Tools Command Prompt`?

**Comment by damuellen** [comment]
D:\Swift\Samples>swift foo.swift
<unknown>:0: error: could not load the swift standard library

**Comment by tinysun212** [comment]
Are you sure you have overwritten the existing directory?
You should be able to see `D:\Swift\usr\lib\swift\mingw;D:\Swift\usr\bin`  from `set PATH [Enter]`.

**Comment by damuellen** [comment]
`Path=D:\Swift\mingw64\bin;D:\Swift\wxWidgets-3.0.3\lib\gcc510TDM_x64_dll;D:\Swift\usr\lib\swift\mingw;D:\Swift\usr\bin;...`

**Comment by tinysun212** [comment]
I could reproduce your message.
The bug seems to appear only on Windows 7.
It is related the function `_create_locale` which is called in the code yesterday inserted and which should be contained in `msvcrt.dll`.
Thank you. Your message has been very helpful in finding the new bug and the cause.

**Comment by damuellen** [comment]
Your welcome. I am happy if I could help.

**Comment by tinysun212** [comment]
Could you test again with https://ci.appveyor.com/project/tinysun212/swift-compiler-builder/build/1.0.13/artifacts?
It calls the function only if it exists.

**Comment by damuellen** [comment]
👍
