### ISSUE TITLE
Could not build C module 'SwiftMinGWCrt'.

### ISSUE THREAD

**Issue by tabokie** [SwiftForWindows/SwiftForWindows#49]
every time I import Foundation module, It can't compile:

<module-includes>:26:10: note: in file included from <module-includes>:26:
#include "../../../../../mingw64/include/regex.h"
         ^
D:\Swift\usr\lib\swift\mingw\x86_64/../../../../../mingw64/include/regex.h:11:10: error: 'tre/tre.h' file not found with <angled> include; use "quotes" instead
#include <tre/tre.h>
         ^
<unknown>:0: error: could not build C module 'SwiftMinGWCrt'

**Comment by tinysun212** [comment]
Could you show me any sample code that generates the error?

**Comment by tabokie** [comment]
Sample code for instance can't work.
================================
import Foundation

let animal = "white rabbit"  
print(animal.contains("rabbit")) // => true  
print(animal.contains("cat"))    // => false

**Comment by tinysun212** [comment]
Could you confirm the existence of the file `D:\Swift\mingw64\include\tre\tre.h` from explorer?

**Comment by tinysun212** [comment]
Could you show me the output `echo %SDKROOTT`?
The environment `SDKROOT` should be cleared.

**Comment by tabokie** [comment]
it's cleared.
echo %SDKROOT%
>> %SDKROOT%

**Comment by tinysun212** [comment]
Are there any other standalone-MinGW version or older version of Swift in your environment?

**Comment by tinysun212** [comment]
Please try to insert module `tre` to the file `D:\Swift\usr\lib\swift\mingw\x86_64\mingw_crt.modulemap`
```
  module C {
    module tre {
      header "../../../../../mingw64/include/tre/tre.h"
      export *
    }

    module assert {
       ...
```

**Comment by tabokie** [comment]
That didn't work.
But I manually change in regex.h from <tre/tre.h> to "tre.tre.h", and it works!
thanks anyway~

**Comment by fwcd** [comment]
Thanks @tabokie , that solved the problem for me too.

**Comment by samlinz** [comment]
I also had this problem, with Swift For Windows 2.0 and Swift 4.1.3 mingw.20181009
The solution described by @tabokie worked for me, too.
