### ISSUE TITLE
Update to Swift 4.1

### ISSUE THREAD

**Issue by YanLiudchyk** [SwiftForWindows/SwiftForWindows#52]
Please can you update Swift to 4.1

**Comment by tinysun212** [comment]
I am glad to see someone waiting for the next version. I found a bug while porting, but I did not have time to fix it with other busy things. I will update it on this weekend.

**Comment by MarkStefanWebb** [comment]
4.2???

**Comment by joeparkerz** [comment]
Try to upload new version! 4.2.0!

**Comment by tinysun212** [comment]
At last, 4.1.3 is ported. You should wait longer for porting of 4.2.
