### ISSUE TITLE
GUI is completely broken on russian version of Windows

### ISSUE THREAD

**Issue by KaCMaHaBT** [SwiftForWindows/SwiftForWindows#6]
There is a problem with fonts, all labels is unreadable.
![image](https://user-images.githubusercontent.com/19468628/29408202-9c08aaa2-8347-11e7-8b0f-d8d2b89b938d.png)
These fonts is not default Windows fonts, I think it gets a random.

**Comment by tinysun212** [comment]
I don't have the Russian version of Windows to test this.
But you can change the unreadable font to readable font by editing the source and compiling it.

1.  Change `wx.BOLD` to `wx.NORMAL` at line 134 in `C:\Swift\Samples\SwiftForWindows\SwiftForWindows.swift`
```C++
  before:   var font_19B = wx.Font(15, wx.DECORATIVE, wx.NORMAL, wx.BOLD)
  after:    var font_19B = wx.Font(15, wx.DECORATIVE, wx.NORMAL, wx.NORMAL)
```

2. Run `C:\Swift\Samples\SwiftForWindows\Build.bat` to compile the source.

3.  Copy `C:\Swift\Samples\SwiftForWindows\SwiftForWindows.exe' to 'C:\Swift' (Overwrite the original file)

If you change the text to Russian, the labels in your program will show in Russian.

**Comment by tinysun212** [comment]
@KaCMaHaBT, did you resolve your problem?
If there is no other problem, may I close this issue?

**Comment by KaCMaHaBT** [comment]
Yes, I think it can be closed.
