### ISSUE TITLE
easiest  way to get libswiftcore.dll

### ISSUE THREAD

**Issue by rmann0581** [SwiftForWindows/SwiftForWindows#8]
I have Swift For Windows 1.6 installed.  I created a swift file with one line of code to test.
print("I have a furry angel in my apartment.")
This file compiles successfully, but when I run it, Windows complains about missing libswiftcore.dll.  What is the easiest way to get this .dll?  I googled Swift for Windows and this project seemed to be the easiest way to get started with to learn Swift except for missing this one .dll file.

**Comment by tinysun212** [comment]
Thanks for using Swift for Windows 1.6.

The DLL should be located in the directory `C:\Swift\usr\lib\swift\mingw`.
If you run the program with the button 'Run', all the necessary DLLs should be loaded.

If you run the program directly in the explorer without updating the environment variable `PATH`, Windows will complain about missing DLLs.

Try again after adding the following path to the environment  variable PATH.
```
C:\Swift\mingw64\bin
C:\Swift\wxWidgets-3.0.3\lib\gcc510TDM_x64_dll
C:\Swift\usr\lib\swift\mingw
C:\Swift\usr\bin
```

**Comment by rmann0581** [comment]
Thank you very much.  My Swift file compiled.
