### ISSUE TITLE
hasSuffix() issue

### ISSUE THREAD

**Issue by gtwade** [SwiftForWindows/SwiftForWindows#9]
Trying to use hasSuffix() throws the following error: value of type 'String' has no member 'hasSuffix'. There is a fix when using Linux (https://stackoverflow.com/questions/40451167/error-value-of-type-string-has-no-member-hassuffix-in-swift-switch), but is there one for Windows?

**Comment by tinysun212** [comment]
The String class is extended by the Foundation module which implemented the member 'hasSuffix'.

The Foundation module is not yet ported to the MinGW version of the Swift which is included in the 'Swift for Windows v1.6'. But the module is ported to the Cygwin version. Please visit https://swiftforwindows.github.io/news/2016/09/13/Swift-for-Windows-Cygwin-20160913/.

To compile and run your program with the Cygwin version, you should install the Cygwin 64bit environment (https://cygwin.com/) and use the command line interface.

1. Installing the Cygwin version of the Swift
```
(in the Cygwin64 terminal)
$ cd /cygdrive/c/Swift
$ tar xvf swift-cygwin-20160913-bin.tar.gz
$ mv swift cygswift
$ export PATH=$PATH:/cygdrive/c/Swift/cygswift/bin
```
2. TestStr.swift
```swift
import Foundation

let vegetable = "red pepper"
switch vegetable {
case "celery":
    print("Add some raisins and make ants on a log.")
case "cucumber", "watercress":
    print("That would make a good tea sandwich.")
case let x where x.hasSuffix("pepper"):
    print("Is it a spicy \(x)?")
default:
    print("Everything tastes good in soup.")
}
```

3. Compiling and Running
```
$ swiftc TestStr.swift -I /usr/include
$ ./TestStr
Is it a spicy red pepper?

$ swift TestStr.swift
Is it a spicy red pepper?
```

Thanks.

**Comment by tinysun212** [comment]
Swift for Windows 1.7 has the Foundation module. Above sample code will work. Please try it and confirm this issue is resolved.

**Comment by tinysun212** [comment]
@gtwade Could you confirm if this bug is resolved?
